"""Frontend-driven supplementary routes.

These endpoints back the Claude Design front-end (Login.html, Platform.html,
Game Console.html). They live in a separate router so the existing api.py
can be edited independently without merge collisions.

Mount in ui.py with:

    from platform_app.frontend_routes import router as frontend_router
    app.include_router(frontend_router)
"""
from __future__ import annotations

import csv
import io
import json
import os
import threading
import time
from datetime import datetime
from pathlib import Path

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse, StreamingResponse

from . import auth as _auth
from .api import (
    SESSION_COOKIE,
    _delete_session_cookie,
    json_response,
    require_user,
)
from .api._deps import is_admin
from .db import connect, expose, init_db
from .perms import owns_save
from .security import hash_password, verify_password

router = APIRouter()

# 历史 SMS stub 已删除 (上线前清理 — 接入真实 SMS 网关需重新设计 OTP 流程)


# ------------------------------------------------------------
#  Helpers
# ------------------------------------------------------------
def _bad(msg: str, status: int = 400):
    return json_response({"ok": False, "error": msg}, status_code=status)


def _client_ip(request: Request) -> str:
    return (request.client.host if request.client else "") or ""


# ------------------------------------------------------------
#  AUTH supplements
# ------------------------------------------------------------
@router.post("/api/auth/password")
async def api_change_password(request: Request):
    """Change current user's password (`current` -> `next`)."""
    user = require_user(request)
    body = await request.json()
    cur_pw = body.get("current") or ""
    next_pw = body.get("next") or ""
    if len(next_pw) < _auth.MIN_PASSWORD_LENGTH:
        return _bad(f"新密码至少 {_auth.MIN_PASSWORD_LENGTH} 位")
    init_db()
    with connect() as db:
        row = db.execute("select password_hash from users where id = %s", (user["id"],)).fetchone()
        if not row:
            return _bad("用户不存在", status=404)
        has_existing_password = bool(row["password_hash"])
        if has_existing_password and not verify_password(cur_pw, row["password_hash"]):
            return _bad("当前密码错误")
        db.execute(
            "update users set password_hash = %s, row_version = row_version + 1, updated_at = now() where id = %s",
            (hash_password(next_pw), user["id"]),
        )
        # Optional: revoke all OTHER sessions (keep current cookie).
        # 用 token_hash 而非明文 token — 新会话 token=''，旧查法对新会话全部静默失效。
        token = request.cookies.get(SESSION_COOKIE)
        if token:
            from .auth import _hash_token
            db.execute(
                "delete from sessions where user_id = %s and token_hash <> %s",
                (user["id"], _hash_token(token)),
            )
    return json_response({"ok": True, "message": "密码已修改" if has_existing_password else "密码已设置"})


@router.get("/api/auth/login-history")
async def api_login_history(request: Request):
    """Return last N login_audit rows for the current user. ?format=csv supported."""
    user = require_user(request)
    init_db()
    fmt = (request.query_params.get("format") or "").lower()
    limit = max(1, min(int(request.query_params.get("limit") or 50), 500))
    with connect() as db:
        db.execute(
            """
            create table if not exists login_audit (
              id bigint generated by default as identity primary key,
              username text, ip text, event text not null,
              meta jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now()
            )
            """
        )
        rows = db.execute(
            """
            select id, username, ip, event, meta, created_at
            from login_audit
            where username = %s
            order by created_at desc
            limit %s
            """,
            (user.get("username"), limit),
        ).fetchall()
    items = [
        {
            "id": r["id"],
            "at": r["created_at"].isoformat() if r["created_at"] else None,
            "ip": r["ip"],
            "user_agent": (r["meta"] or {}).get("ua") if isinstance(r["meta"], dict) else None,
            "result": "ok" if r["event"] == "login_ok" else "blocked",
            "event": r["event"],
        }
        for r in rows
    ]
    if fmt == "csv":
        buf = io.StringIO()
        w = csv.writer(buf)
        w.writerow(["at", "ip", "event", "result"])
        for i in items:
            w.writerow([i.get("at"), i.get("ip"), i.get("event"), i.get("result")])
        return StreamingResponse(
            io.BytesIO(buf.getvalue().encode("utf-8")),
            media_type="text/csv; charset=utf-8",
            headers={"Content-Disposition": 'attachment; filename="login-history.csv"'},
        )
    return json_response({"ok": True, "entries": items})


@router.get("/api/auth/sessions")
async def api_list_sessions(request: Request):
    user = require_user(request)
    init_db()
    from .auth import _hash_token
    cur_token = request.cookies.get(SESSION_COOKIE) or ""
    cur_hash = _hash_token(cur_token) if cur_token else ""
    with connect() as db:
        rows = db.execute(
            """
            select token_hash, user_id, created_at, expires_at
            from sessions
            where user_id = %s and expires_at > now()
            order by created_at desc
            """,
            (user["id"],),
        ).fetchall()
    out = []
    for r in rows:
        thash = r["token_hash"] or ""
        # P1-2 方案B: 使用前 24 位作为可见 session ID（96 bit，碰撞概率极低），替代原 12 位
        display_id = thash[:24] if thash else ""
        out.append({
            "id": display_id,
            "session_id": display_id,
            "created_at": r["created_at"].isoformat() if r["created_at"] else None,
            "expires_at": r["expires_at"].isoformat() if r["expires_at"] else None,
            "last_seen_at": r["created_at"].isoformat() if r["created_at"] else None,
            "current": bool(cur_hash) and thash == cur_hash,
        })
    return json_response({"ok": True, "sessions": out})


@router.post("/api/auth/sessions/revoke")
async def api_revoke_session(request: Request):
    user = require_user(request)
    body = await request.json()
    sid = body.get("session_id") or body.get("id") or ""
    if not sid:
        return _bad("缺少 session_id")
    init_db()
    from .auth import _hash_token
    cur_token = request.cookies.get(SESSION_COOKIE) or ""
    cur_hash = _hash_token(cur_token) if cur_token else ""
    # P1-2 方案B: sid 已是前 24 位前缀，用 startswith 精确前缀匹配代替后缀 LIKE 碰撞
    if len(sid) != 24 or not all(c in "0123456789abcdef" for c in sid):
        return _bad("无效的 session_id 格式")
    with connect() as db:
        # 用 token_hash 前 24 位前缀精确匹配；当前会话不能被自我吊销
        deleted = db.execute(
            "delete from sessions where user_id = %s and left(token_hash, 24) = %s and token_hash <> %s returning token_hash",
            (user["id"], sid, cur_hash),
        ).fetchone()
    return json_response({"ok": True, "deleted": bool(deleted)})


@router.post("/api/auth/sessions/revoke-all")
async def api_revoke_all_sessions(request: Request):
    user = require_user(request)
    init_db()
    from .auth import _hash_token
    cur_token = request.cookies.get(SESSION_COOKIE) or ""
    cur_hash = _hash_token(cur_token) if cur_token else ""
    with connect() as db:
        n = db.execute(
            "delete from sessions where user_id = %s and token_hash <> %s",
            (user["id"], cur_hash),
        ).statusmessage
    return json_response({"ok": True, "result": n})



# ------------------------------------------------------------
#  PROFILE supplements
# ------------------------------------------------------------
# 头像落盘统一走 storage 模块（S1 基座）
from .storage import AVATARS_DIR as _AVATARS_DIR
from .storage import resolve_path as _storage_resolve_path
from .storage import store_bytes as _storage_store_bytes


@router.post("/api/profile/avatar")
async def api_upload_avatar(request: Request):
    user = require_user(request)
    form = await request.form()
    f = form.get("file")
    if not f or not getattr(f, "filename", ""):
        return _bad("请选择文件")
    ext = os.path.splitext(f.filename or "")[-1].lower()
    if ext not in {".png", ".jpg", ".jpeg", ".webp"}:
        return _bad("仅支持 PNG / JPG / WEBP")
    data = await f.read()
    if len(data) > 2 * 1024 * 1024:
        return _bad("文件超过 2 MB")
    # 魔数校验:不信客户端文件名扩展名,以真实图片字节为准(与角色卡/人设图/卡导入
    # 三处上传一致,见 api/me.py:_detect_image_mime)。伪造扩展名的非图片 → 400,
    # 落盘扩展名取检测结果(防止任意字节伪装成 .png 进头像图床并以 image/* 回发)。
    from .api.me import _detect_image_mime
    try:
        _mime, _detected_ext = _detect_image_mime(data)
    except ValueError as exc:
        return _bad(str(exc))
    safe_name = f"u{user['id']}_{int(time.time())}.{_detected_ext}"
    # 落盘走 storage.store_bytes（统一根 AVATARS_DIR）
    _storage_key, _new_url = _storage_store_bytes(data, kind="avatars", filename=safe_name)
    # 对外 URL 仍用旧路径保持向后兼容，前端老 URL 不破
    avatar_url = f"/api/profile/avatar/file/{safe_name}"
    init_db()
    with connect() as db:
        db.execute(
            "update users set avatar_url = %s, updated_at = now() where id = %s",
            (avatar_url, user["id"]),
        )
    # 登记 user_assets（失败只 log，不影响上传主流程）
    try:
        from platform_app.assets_registry import register_asset  # lazy import
        register_asset(
            user_id=int(user["id"]),
            kind="avatar",
            storage_key=f"avatars/{safe_name}",
            url=avatar_url,
            source="avatar_upload",
            ref_kind="user",
            ref_id=int(user["id"]),
            mime=_mime,
            size=len(data),
        )
    except Exception as _reg_exc:
        import logging as _logging
        _logging.getLogger(__name__).warning(
            "[frontend_routes] register_asset(avatar) failed user=%s: %s",
            user["id"], _reg_exc,
        )
    return json_response({"ok": True, "avatar_url": avatar_url})


@router.post("/api/profile/avatar-url")
async def api_set_avatar_url(request: Request):
    """从图库 URL 设置个人头像（不重新上传，URL 已是合法资产）。

    URL 前缀白名单：复用 _safe_avatar_path；非法 URL → 400。
    """
    from platform_app.user_cards import _safe_avatar_path

    user = require_user(request)
    body = await request.json()
    raw_url = str(body.get("url") or "").strip()
    safe_url = _safe_avatar_path(raw_url)
    if not safe_url:
        return json_response({"ok": False, "error": "不合法的图片 URL（仅允许站内资产路径）"}, status_code=400)

    init_db()
    with connect() as db:
        db.execute(
            "update users set avatar_url = %s, updated_at = now() where id = %s",
            (safe_url, user["id"]),
        )
    return json_response({"ok": True, "url": safe_url})


@router.post("/api/profile/avatar/reset")
async def api_reset_avatar(request: Request):
    user = require_user(request)
    init_db()
    with connect() as db:
        db.execute("update users set avatar_url = null, updated_at = now() where id = %s", (user["id"],))
    return json_response({"ok": True})


@router.get("/api/profile/avatar/file/{name}")
async def api_avatar_file(name: str, request: Request):
    # 鉴权链接:必须登录(cookie)才能取图,未登录 → 401(同 /api/storage、/api/images/file)。
    require_user(request)
    # Basic safety: only allow our generated naming pattern.
    if "/" in name or "\\" in name or name.startswith("."):
        raise HTTPException(404)
    # 服务改走 storage.resolve_path（统一根 AVATARS_DIR），老 URL 保持兼容
    try:
        path = _storage_resolve_path(f"avatars/{name}")
    except ValueError:
        raise HTTPException(404)
    if not path.exists():
        raise HTTPException(404)
    return FileResponse(str(path))


def _ensure_profile_extras_table() -> None:
    # v33 migration 已建表，懒创建废弃。保留空函数避免 me.py / platform.py 的导入报错。
    pass


@router.post("/api/profile/visibility")
async def api_profile_visibility(request: Request):
    user = require_user(request)
    body = await request.json() or {}
    from psycopg.types.json import Jsonb
    with connect() as db:
        db.execute(
            """
            insert into profile_extras(user_id, visibility)
            values (%s, %s)
            on conflict (user_id) do update set visibility = excluded.visibility, updated_at = now()
            """,
            (user["id"], Jsonb(body)),
        )
    return json_response({"ok": True, "visibility": body})


# Persist any additional “me/preference” keys here too.
@router.post("/api/me/preference")
async def api_save_preference(request: Request):
    user = require_user(request)
    body = await request.json() or {}
    from psycopg.types.json import Jsonb
    # Merge over existing preferences
    with connect() as db:
        row = db.execute(
            "select preferences from profile_extras where user_id = %s",
            (user["id"],),
        ).fetchone()
        prefs = (row and row["preferences"]) or {}
        prefs.update(body)
        db.execute(
            """
            insert into profile_extras(user_id, preferences)
            values (%s, %s)
            on conflict (user_id) do update set preferences = excluded.preferences, updated_at = now()
            """,
            (user["id"], Jsonb(prefs)),
        )
    return json_response({"ok": True, "preferences": prefs})


# 注:GET /api/me/profile 已统一到 platform_app/api/me.py(返回 user+profile+extras+
# 偏好+用量+凭证,超集)。此处原有的重复路由会被 platform_router(先挂载)遮蔽,
# 已删除以消除路由冲突。


# ------------------------------------------------------------
#  ACCOUNT lifecycle
# ------------------------------------------------------------

# LC-05: /api/account/export — 同步返回完整用户数据 JSON.
# 若 B12 邮件 util 落地后可改为异步任务+邮件发链接；当前同步 stream 返回 zip。
@router.get("/api/account/export")
async def api_account_export(request: Request):
    """返回当前用户全量数据，JSON 格式，作为可下载文件（LC-05）."""
    import zipfile

    user = require_user(request)
    uid = user["id"]
    init_db()

    with connect() as db:
        # 用户基本信息
        u_row = db.execute(
            "select id, username, email, created_at, updated_at, deactivated_at, public_id from users where id = %s",
            (uid,),
        ).fetchone()
        pe_row = db.execute("select * from profile_extras where user_id = %s", (uid,)).fetchone()
        prefs_row = db.execute("select preferences from user_preferences where user_id = %s", (uid,)).fetchone()

        # 存档 / 角色卡
        saves = db.execute(
            "select id, title, created_at, updated_at, last_played_at from game_saves where user_id = %s order by updated_at desc",
            (uid,),
        ).fetchall()
        save_ids = [s["id"] for s in saves]

        # branch_commits（属于用户存档）
        commits: list = []
        for sid in save_ids:
            rows = db.execute(
                "select id, save_id, turn_index, kind, title, message, created_at from branch_commits where save_id = %s order by turn_index",
                (sid,),
            ).fetchall()
            commits.extend(rows)

        cards = db.execute(
            "select id, name, card_type, source, created_at from character_cards where user_id = %s",
            (uid,),
        ).fetchall()

        # 用量 / 审计
        usage = db.execute(
            "select id, api_id, model_real_name, total_tokens, cost_usd, created_at from token_usage where user_id = %s order by created_at desc limit 1000",
            (uid,),
        ).fetchall()
        audit = db.execute(
            "select id, event, ip, created_at from login_audit where username = %s order by created_at desc limit 500",
            (user.get("username", ""),),
        ).fetchall()

        # 记忆
        memories = db.execute(
            "select id, bucket, content, importance, created_at from memories where user_id = %s order by created_at desc",
            (uid,),
        ).fetchall()

    def _to_list(rows) -> list:
        if rows is None:
            return []
        return [dict(r) for r in rows]

    def _to_dict(row) -> dict:
        return dict(row) if row else {}

    payload = {
        "export_version": "1",
        "user": _to_dict(u_row),
        "profile_extras": _to_dict(pe_row),
        "preferences": _to_dict(prefs_row),
        "game_saves": _to_list(saves),
        "branch_commits": _to_list(commits),
        "character_cards": _to_list(cards),
        "token_usage": _to_list(usage),
        "login_audit": _to_list(audit),
        "memories": _to_list(memories),
    }

    # 序列化 datetime/uuid 对象
    import datetime as _dt
    import uuid as _uuid

    def _default(obj):
        if isinstance(obj, (_dt.datetime, _dt.date)):
            return obj.isoformat()
        if isinstance(obj, _uuid.UUID):
            return str(obj)
        raise TypeError(f"Object of type {type(obj)} is not JSON serializable")

    raw_json = json.dumps(payload, default=_default, ensure_ascii=False, indent=2).encode("utf-8")

    # 打成 zip，方便扩展多文件
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("account_data.json", raw_json)
    buf.seek(0)

    username = user.get("username", str(uid))
    filename = f"account_export_{username}.zip"
    return StreamingResponse(
        buf,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


# LC-05: 兼容 POST（旧版客户端）— 重定向到同步 GET 导出
@router.post("/api/account/export")
async def api_account_export_post(request: Request):
    """POST 兼容层：直接调同步导出逻辑（LC-05）."""
    return await api_account_export(request)


# LC-01: 软停用（可恢复）
@router.post("/api/account/deactivate")
async def api_account_deactivate(request: Request):
    """软停用账号（可恢复）。立刻置 deactivated_at，注销所有 session。"""
    user = require_user(request)
    init_db()
    with connect() as db:
        db.execute(
            "update users set deactivated_at = now(), updated_at = now() where id = %s",
            (user["id"],),
        )
        db.execute("delete from sessions where user_id = %s", (user["id"],))
    return json_response({"ok": True})


# LC-01: 硬删请求（30 天宽限期）
@router.post("/api/account/request-delete")
async def api_account_request_delete(request: Request):
    """申请硬删账号，写入 account_delete_queue，30 天后由 cron 物理删除（LC-01）."""
    user = require_user(request)
    body: dict = {}
    try:
        body = await request.json() or {}
    except Exception:
        pass
    reason = body.get("reason", "user-requested")
    ip = request.client.host if request.client else ""
    init_db()
    with connect() as db:
        # 幂等：若已有未完成的队列行，直接返回现有计划时间
        existing = db.execute(
            "select scheduled_hard_delete_at from account_delete_queue where user_id = %s and completed_at is null",
            (user["id"],),
        ).fetchone()
        if existing:
            return json_response({
                "ok": True,
                "scheduled_hard_delete_at": existing["scheduled_hard_delete_at"].isoformat()
                if hasattr(existing["scheduled_hard_delete_at"], "isoformat")
                else str(existing["scheduled_hard_delete_at"]),
                "message": "删除请求已存在，30 天宽限期内可撤销",
            })

        db.execute(
            """
            insert into account_delete_queue
              (user_id, requested_at, scheduled_hard_delete_at, requested_by_ip, reason)
            values
              (%s, now(), now() + interval '30 days', %s, %s)
            on conflict (user_id) do update
              set requested_at = now(),
                  scheduled_hard_delete_at = now() + interval '30 days',
                  requested_by_ip = excluded.requested_by_ip,
                  reason = excluded.reason,
                  completed_at = null
            """,
            (user["id"], ip, reason),
        )
        # 立刻停用，用户不能再登录
        db.execute(
            "update users set deactivated_at = now(), updated_at = now() where id = %s",
            (user["id"],),
        )
        db.execute("delete from sessions where user_id = %s", (user["id"],))
        row = db.execute(
            "select scheduled_hard_delete_at from account_delete_queue where user_id = %s",
            (user["id"],),
        ).fetchone()

    sched = row["scheduled_hard_delete_at"] if row else None
    sched_str = sched.isoformat() if hasattr(sched, "isoformat") else str(sched)

    # TODO(B12): 发邮件确认 + 30 天倒计时链接（B12 邮件 util 落地后接入）

    resp = json_response({
        "ok": True,
        "scheduled_hard_delete_at": sched_str,
        "message": "删除申请已提交，30 天内可撤销。如需取消请调用 /api/account/cancel-delete。",
    })
    _delete_session_cookie(resp, request)
    return resp


# LC-01: 撤销硬删（宽限期内）
@router.post("/api/account/cancel-delete")
async def api_account_cancel_delete(request: Request):
    """在 30 天宽限期内撤销硬删请求（LC-01）。需要用户仍能通过 session 鉴权。"""
    user = require_user(request)
    init_db()
    with connect() as db:
        queue_row = db.execute(
            "select user_id from account_delete_queue where user_id = %s and completed_at is null",
            (user["id"],),
        ).fetchone()
        if not queue_row:
            return _bad("没有进行中的删除请求，或已超过宽限期", 404)
        # 撤销：删队列行 + 清 deactivated_at
        db.execute("delete from account_delete_queue where user_id = %s", (user["id"],))
        db.execute(
            "update users set deactivated_at = null, updated_at = now() where id = %s",
            (user["id"],),
        )
    return json_response({"ok": True, "message": "删除申请已撤销，账号已恢复正常。"})


# LC-01: 查询删除状态
@router.get("/api/account/delete-status")
async def api_account_delete_status(request: Request):
    """查询当前账号删除状态（none / soft-deactivated / hard-pending）（LC-01）."""
    user = require_user(request)
    init_db()
    with connect() as db:
        u_row = db.execute(
            "select deactivated_at from users where id = %s",
            (user["id"],),
        ).fetchone()
        queue_row = db.execute(
            "select scheduled_hard_delete_at, requested_at from account_delete_queue where user_id = %s and completed_at is null",
            (user["id"],),
        ).fetchone()

    deactivated_at = u_row["deactivated_at"] if u_row else None

    if queue_row:
        sched = queue_row["scheduled_hard_delete_at"]
        return json_response({
            "status": "hard-pending",
            "scheduled_hard_delete_at": sched.isoformat() if hasattr(sched, "isoformat") else str(sched),
            "requested_at": queue_row["requested_at"].isoformat() if hasattr(queue_row["requested_at"], "isoformat") else str(queue_row["requested_at"]),
        })
    if deactivated_at:
        return json_response({
            "status": "soft-deactivated",
            "deactivated_at": deactivated_at.isoformat() if hasattr(deactivated_at, "isoformat") else str(deactivated_at),
        })
    return json_response({"status": "none"})


# 保留旧 /api/account/delete 端点（向后兼容），行为等同 request-delete
@router.post("/api/account/delete")
async def api_account_delete(request: Request):
    """已废弃，保留向后兼容。等同于 /api/account/request-delete（30 天宽限期）."""
    return await api_account_request_delete(request)


# ------------------------------------------------------------
#  SAVES supplements
# ------------------------------------------------------------
@router.post("/api/saves/{save_id}/delete")
async def api_save_delete(save_id: int, request: Request):
    user = require_user(request)
    init_db()
    with connect() as db:
        if not owns_save(db, save_id, user["id"]):
            return _bad("无权操作该存档", 403)
        db.execute("delete from game_saves where id = %s and user_id = %s", (save_id, user["id"]))
    return json_response({"ok": True})


@router.post("/api/saves/{save_id}/rename")
async def api_save_rename(save_id: int, request: Request):
    user = require_user(request)
    body = await request.json()
    title = (body.get("title") or "").strip()
    if not title:
        return _bad("标题不能为空")
    init_db()
    with connect() as db:
        if not owns_save(db, save_id, user["id"]):
            return _bad("无权操作该存档", 403)
        db.execute(
            "update game_saves set title = %s, updated_at = now() where id = %s",
            (title, save_id),
        )
    return json_response({"ok": True, "title": title})


@router.post("/api/saves/{save_id}/activate")
async def api_save_activate(save_id: int, request: Request):
    """task 30：之前只 select 1 验证归属就返 ok=True，既不写 user_runtime，
    也不清 ui._state_by_user 缓存 → 用户点完「继续」跳到 Game Console，
    GET /api/state 拿到的是上一个 active save 的 player/world。

    现在：调用 branches.activate_save → runtime.activate_state_snapshot
    把 user_runtime 切到目标 save 的 active commit；并清掉 ui 进程内 state 缓存，
    下一次 _ensure_loaded 会从 user_runtime 重新加载新 save 的 state。"""
    user = require_user(request)
    from . import branches as _branches
    try:
        result = _branches.activate_save(user["id"], save_id)
    except ValueError as exc:
        return _bad(str(exc), 403)
    # 清 ui 模块内的 per-user state 缓存（跨模块耦合：ui 在主进程内长期持有 cache，
    # activate 必须告诉它丢掉旧 save 的 state，否则 GET /api/state 仍读旧档）。
    try:
        import app as _ui
        _ui._invalidate_user_cache(user)
    except Exception:
        pass
    return json_response(result)


@router.get("/api/saves/{save_id}/export")
async def api_save_export(save_id: int, request: Request):
    user = require_user(request)
    init_db()
    with connect() as db:
        # 归属判定收敛到 perms.owns_save;不属返 404(沿用原契约,不暴露存在性)。
        if not owns_save(db, save_id, user["id"]):
            raise HTTPException(404)
        row = db.execute(
            "select id, title, state_snapshot, created_at, updated_at from game_saves where id = %s",
            (save_id,),
        ).fetchone()
    if not row:
        raise HTTPException(404)
    payload = {
        "id": row["id"],
        "title": row["title"],
        "exported_at": datetime.now().isoformat(),
        "state": row["state_snapshot"],
    }
    body = json.dumps(payload, ensure_ascii=False, indent=2)
    safe_title = (row["title"] or f"save-{save_id}").replace("/", "_")
    return StreamingResponse(
        io.BytesIO(body.encode("utf-8")),
        media_type="application/json; charset=utf-8",
        headers={"Content-Disposition": f'attachment; filename="{safe_title}.json"'},
    )


# ------------------------------------------------------------
#  CHARACTER CARDS supplements
# ------------------------------------------------------------
@router.post("/api/me/character-cards/import-json")
async def api_card_import_json(request: Request):
    user = require_user(request)
    body = await request.json() or {}
    raw = body.get("json") or ""
    try:
        data = json.loads(raw) if isinstance(raw, str) else raw
    except Exception as e:
        return _bad(f"JSON 解析失败：{e}")
    # Accept a variety of shapes (SillyTavern v1/v2 etc.)
    # 解包常见的外层包装（如 {"ok":true,"card":{...}}）
    if isinstance(data, dict) and not data.get("name") and not data.get("char_name"):
        for key in ("card", "character", "chara_card"):
            inner = data.get(key)
            if isinstance(inner, dict) and (inner.get("name") or inner.get("data", {}).get("name")):
                data = inner
                break
    name = data.get("name") or data.get("char_name") or ""
    if not name and isinstance(data.get("data"), dict):
        name = data["data"].get("name") or ""
    if not name:
        return _bad("缺少 name 字段")
    from . import user_cards as _uc
    card = _uc.upsert_user_card(user["id"], {
        "name": name,
        "description": data.get("description") or data.get("personality") or "",
        "first_message": data.get("first_mes") or data.get("first_message") or "",
        "tags": data.get("tags") or [],
        "source": "import-json",
    })
    return json_response({"ok": True, "card": card})


# ------------------------------------------------------------
#  MODELS supplements (visibility & validate)
# ------------------------------------------------------------
@router.post("/api/models/visibility")
async def api_models_visibility(request: Request):
    """Toggle visibility flags for individual models.

    Writes through upsert_model so DB + JSON catalog stay in sync.
    Previously wrote only to model_entries.enabled, which diverged from the
    catalog JSON on restart when DB was unavailable.
    """
    # 全局模型目录写操作:与同级 /api/models/* 一致,须管理员(CWE-862)。
    user = require_user(request)
    if not is_admin(user):
        return _bad("需要管理员权限", status=403)
    body = await request.json() or {}
    api_id = body.get("api_id") or body.get("api")
    model_real_name = body.get("model") or body.get("real_name")
    visible = body.get("visible")
    if not api_id or model_real_name is None or visible is None:
        return _bad("缺少参数")
    from model_registry import find_api, load_model_catalog, upsert_model
    catalog = load_model_catalog()
    api = find_api(catalog, api_id)
    if not api:
        return _bad(f"未知 API: {api_id}")
    # locate model by real_name or id
    model_entry = next(
        (m for m in api.get("models", []) if m.get("real_name") == model_real_name or m.get("id") == model_real_name),
        None,
    )
    if not model_entry:
        return _bad(f"模型不存在: {model_real_name}")
    # upsert_model merges into catalog and calls save_model_catalog (writes DB + JSON)
    upsert_model(api_id, {**model_entry, "enabled": bool(visible)})
    return json_response({"ok": True})


@router.post("/api/me/models/visibility")
async def api_me_models_visibility(request: Request):
    """每用户:隐藏/显示自己【同步来的】单个模型(user_model_entries.enabled)。

    与上面 /api/models/visibility(admin、写全局 model_entries)不同 —— 这个任何用户都能调,
    只动自己的 overlay。用户「启用某 provider(如 openrouter)但只想留几个模型」靠这个,
    且 set 后下次 remote/sync 不会被重置(见 user_models.replace_synced_models 的 prev 保留)。
    body: {api_id, model(=model_id 或 real_name), visible: bool}
    """
    user = require_user(request)
    body = await request.json() or {}
    api_id = body.get("api_id") or body.get("api")
    model = body.get("model") or body.get("real_name") or body.get("model_id")
    visible = body.get("visible")
    if not api_id or model is None or visible is None:
        return _bad("缺少参数")
    from platform_app.user_models import set_overlay_model_enabled
    n = set_overlay_model_enabled(user["id"], api_id, model, bool(visible))
    if not n:
        return _bad("该模型不在你的同步清单里(只能隐藏你自己同步来的模型)", status=404)
    return json_response({"ok": True, "updated": n})


@router.post("/api/models/validate")
async def api_models_validate(request: Request):
    """Lightweight credentials probe — defers to model_probe.list_remote_models."""
    user = require_user(request)
    body = await request.json() or {}
    api_id = body.get("api_id") or body.get("api_slug") or body.get("api") or ""
    try:
        from model_probe import list_remote_models, probe_availability
        if body.get("model"):
            out = probe_availability(
                api_id=api_id,
                model_real_name=body.get("model"),
                user_id=user["id"],
                timeout_sec=int(body.get("timeout", 8)),
            )
        else:
            out = list_remote_models(api_id=api_id, force_refresh=True, user_id=user["id"])
        return json_response({"ok": True, **(out if isinstance(out, dict) else {"result": out})})
    except Exception as e:
        return json_response({"ok": False, "error": str(e)}, status_code=400)


# ------------------------------------------------------------
#  SEARCH
# ------------------------------------------------------------
# 合法 scope 值。"all" 表示不过滤。
_SEARCH_SCOPES = frozenset({"all", "scripts", "saves", "cards", "worldbook", "memories", "npc_cards"})


@router.get("/api/search")
async def api_search(request: Request):
    """Cross-resource search. Returns grouped results per resource kind.

    Query params:
      q      — search term (required, min 1 char after strip)
      scope  — one of: all (default) | scripts | saves | cards |
               worldbook | memories | npc_cards
               Restricts the search to that group only.

    Response shape:
      {
        "ok": true,
        "query": "<q>",
        "scope": "<scope>",
        "groups": [
          {
            "kind": "scripts" | "saves" | "cards" | "worldbook" | "memories" | "npc_cards",
            "items": [
              {
                "id": <int>,
                "label": "<primary text>",
                "sub": "<secondary text, may be absent>",
                "href": "<deep-link, may be absent>"
              },
              ...
            ]
          },
          ...
        ]
      }

    Performance note (worldbook / memories):
      ILIKE '%q%' scans are used here because gin_trgm_ops indexes are not
      yet applied to worldbook_entries / memories.
      # TODO: 待 migrations.py 解锁后加 gin_trgm_ops 索引到
      #        worldbook_entries(title, content) 和 memories(content)
    """
    user = require_user(request)
    q = (request.query_params.get("q") or "").strip()
    if not q:
        return json_response({"ok": True, "query": "", "scope": "all", "groups": []})

    raw_scope = (request.query_params.get("scope") or "all").strip().lower()
    scope = raw_scope if raw_scope in _SEARCH_SCOPES else "all"

    pattern = f"%{q}%"
    init_db()
    groups = []

    def _want(kind: str) -> bool:
        return scope == "all" or scope == kind

    with connect() as db:
        # --- scripts ---
        if _want("scripts"):
            scripts = db.execute(
                "select id, title, description from scripts "
                "where owner_id = %s and title ilike %s limit 8",
                (user["id"], pattern),
            ).fetchall()
            if scripts:
                groups.append({"kind": "scripts", "items": [
                    {"id": r["id"], "label": r["title"], "sub": r["description"],
                     "href": "/scripts"}
                    for r in scripts
                ]})

        # --- saves ---
        if _want("saves"):
            saves = db.execute(
                "select id, title from game_saves where user_id = %s and title ilike %s limit 8",
                (user["id"], pattern),
            ).fetchall()
            if saves:
                groups.append({"kind": "saves", "items": [
                    {"id": r["id"], "label": r["title"], "href": "/saves"}
                    for r in saves
                ]})

        # --- cards (PC + persona, owned by user) ---
        if _want("cards"):
            try:
                # v28: character_cards 多态后 owner_user_id 列已不存在(改名 user_id);
                # 全局搜索仅搜自己的 PC 卡 + persona(NPC 卡按 script_id 隔离,不属于"我的"维度)。
                cards = db.execute(
                    "select id, name from character_cards "
                    "where user_id = %s and card_type in ('pc','persona') and name ilike %s limit 8",
                    (user["id"], pattern),
                ).fetchall()
                if cards:
                    groups.append({"kind": "cards", "items": [
                        {"id": r["id"], "label": r["name"], "href": "/cards"}
                        for r in cards
                    ]})
            except Exception:
                pass

        # --- worldbook (entries belonging to user's scripts) ---
        if _want("worldbook"):
            try:
                # Join via scripts to restrict to entries the user owns.
                # TODO: 待 migrations.py 解锁后加 gin_trgm_ops 索引到 worldbook_entries(title, content)
                wb_rows = db.execute(
                    """
                    select we.id, we.title, left(we.content, 120) as snippet, we.script_id
                    from worldbook_entries we
                    join scripts s on s.id = we.script_id
                    where s.owner_id = %s
                      and (we.title ilike %s or we.content ilike %s)
                    order by we.priority desc
                    limit 8
                    """,
                    (user["id"], pattern, pattern),
                ).fetchall()
                if wb_rows:
                    groups.append({"kind": "worldbook", "items": [
                        {
                            "id": r["id"],
                            "label": r["title"],
                            "sub": r["snippet"],
                            "href": f"/scripts?script={r['script_id']}",
                        }
                        for r in wb_rows
                    ]})
            except Exception:
                pass

        # --- memories (rows in `memories` table owned by user) ---
        if _want("memories"):
            try:
                # TODO: 待 migrations.py 解锁后加 gin_trgm_ops 索引到 memories(content)
                mem_rows = db.execute(
                    """
                    select id, bucket, left(content, 120) as snippet
                    from memories
                    where user_id = %s and content ilike %s
                    order by importance desc, updated_at desc
                    limit 8
                    """,
                    (user["id"], pattern),
                ).fetchall()
                if mem_rows:
                    groups.append({"kind": "memories", "items": [
                        {
                            "id": r["id"],
                            "label": r["bucket"],
                            "sub": r["snippet"],
                        }
                        for r in mem_rows
                    ]})
            except Exception:
                pass

        # --- npc_cards (NPC cards within user's scripts) ---
        if _want("npc_cards"):
            try:
                # character_cards has no 'bio' column; use identity + personality as searchable text.
                npc_rows = db.execute(
                    """
                    select cc.id, cc.name,
                           left(coalesce(nullif(cc.identity,''), cc.personality, ''), 120) as snippet,
                           cc.script_id
                    from character_cards cc
                    join scripts s on s.id = cc.script_id
                    where s.owner_id = %s
                      and cc.card_type = 'npc'
                      and (cc.name ilike %s or cc.identity ilike %s or cc.personality ilike %s)
                    limit 8
                    """,
                    (user["id"], pattern, pattern, pattern),
                ).fetchall()
                if npc_rows:
                    groups.append({"kind": "npc_cards", "items": [
                        {
                            "id": r["id"],
                            "label": r["name"],
                            "sub": r["snippet"],
                            "href": f"/cards?script={r['script_id']}",
                        }
                        for r in npc_rows
                    ]})
            except Exception:
                pass

    return json_response({"ok": True, "query": q, "scope": scope, "groups": groups})


# ------------------------------------------------------------
#  Plugins / Skills lists (frontend convenience)
# ------------------------------------------------------------
@router.get("/api/plugins")
async def api_plugins(request: Request):
    """Reuse /api/tools but slice the 'plugins' channel for the CapPage."""
    from tools_dsl.tool_registry import tool_payload
    payload = tool_payload()
    return json_response({"ok": True, "plugins": payload.get("plugins", [])})


@router.get("/api/skills")
async def api_skills_list(request: Request):
    require_user(request)
    from tools_dsl.tool_registry import tool_payload
    payload = tool_payload()
    return json_response({"ok": True, "skills": payload.get("skills", [])})


# ------------------------------------------------------------
#  Admin: SMTP test (button in DeploySection)
# ------------------------------------------------------------
@router.post("/api/admin/smtp/test")
async def api_admin_smtp_test(request: Request):
    """task 51：FE DeploySection 有「发送测试邮件」按钮但后端从未实现。
    返回明确的"未配置"错误，让 UI 显示真实失败而不是 404 黑洞。

    真正实现需要：读 user_preferences (SMTP host/port/user/pass/from) →
    smtplib.SMTP(host, port).login(user, pass).sendmail(from, to, msg)。
    现在 SMTP 配置还存在 user_preferences 待规范化阶段，先给清晰的占位错误。
    """
    user = require_user(request)
    if not is_admin(user):
        return json_response({"ok": False, "error": "需要管理员权限"}, status_code=403)
    return json_response({
        "ok": False,
        "error": "SMTP 尚未在 user_preferences 中规范化存储 · 请先在「部署 → 邮件 SMTP」配置并保存",
        "configured": False,
    }, status_code=503)


# ------------------------------------------------------------
#  Admin: Deployment config (SMTP, CORS, listen addr, CAPTCHA…)
# ------------------------------------------------------------
_DEPLOY_CFG_KEY = "admin.deployment_config"


@router.get("/api/admin/deployment-config")
async def api_admin_deployment_config_get(request: Request):
    """读取管理员部署配置（存于 app_config 表）。需要重启才能生效。"""
    user = require_user(request)
    if not is_admin(user):
        return json_response({"ok": False, "error": "需要管理员权限"}, status_code=403)
    init_db()
    with connect() as db:
        row = db.execute(
            "select value from app_config where key = %s", (_DEPLOY_CFG_KEY,)
        ).fetchone()
    cfg = dict(row["value"]) if row else {}
    return json_response({"ok": True, "config": cfg})


@router.post("/api/admin/deployment-config")
async def api_admin_deployment_config_set(request: Request):
    """保存管理员部署配置（SMTP / CORS / 监听地址 / CAPTCHA）到 app_config。

    采用 patch 合并语义：只更新 body 中出现的键，不影响其他键。
    注意：listen_address / cors_origins 等网络级配置需要重启服务才能生效。
    """
    from psycopg.types.json import Jsonb

    user = require_user(request)
    if not is_admin(user):
        return json_response({"ok": False, "error": "需要管理员权限"}, status_code=403)
    body = await request.json() or {}
    if not isinstance(body, dict):
        return _bad("请求体必须是对象")
    init_db()
    with connect() as db:
        row = db.execute(
            "select value from app_config where key = %s", (_DEPLOY_CFG_KEY,)
        ).fetchone()
        existing = dict(row["value"]) if row else {}
        merged = {**existing, **body}
        db.execute(
            """
            insert into app_config(key, value)
            values (%s, %s)
            on conflict(key) do update set value = excluded.value, updated_at = now()
            """,
            (_DEPLOY_CFG_KEY, Jsonb(merged)),
        )
    return json_response({"ok": True, "config": merged,
                          "note": "listen_address / cors_origins 等网络配置需重启服务才能生效"})
