// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../../rust/crates/rpg-llm/bindings/serde_json/JsonValue";
import type { ChatMessage } from "./ChatMessage";
import type { ToolSchema } from "./ToolSchema";

export type ChatRequest = { model: string, system?: string | null, messages: Array<ChatMessage>, tools?: Array<ToolSchema>, temperature?: number | null, max_tokens?: number | null, 
/**
 * true 时 stream_chat 返回逐 token 的 chunk;false 时一次性返回。
 */
stream: boolean, 
/**
 * provider 特定补丁 (anthropic cache_control / vertex thinking_budget / openai response_format 等)
 */
extra: JsonValue, };
