// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../../rust/crates/rpg-llm/bindings/serde_json/JsonValue";
import type { ChatRole } from "./ChatRole";
import type { MessagePart } from "./MessagePart";
import type { ToolCall } from "./ToolCall";

/**
 * 同一条消息可以是纯文本,也可以是 multipart (image / tool_result / tool_use)。
 * `extra` 用来透传 provider 特定字段 (e.g. cache_control)。
 */
export type ChatMessage = { role: ChatRole, content?: string | null, parts?: Array<MessagePart>, 
/**
 * 当 role=tool 时使用 (OpenAI 兼容)。
 */
tool_call_id?: string | null, 
/**
 * 当 role=assistant 且包含 tool_use 时,这里是 assistant 调用的 tool。
 */
tool_calls?: Array<ToolCall>, 
/**
 * provider 特定附加字段 (Anthropic cache_control 等)。
 */
extra?: JsonValue, };
