// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../../rust/crates/rpg-llm/bindings/serde_json/JsonValue";

export type MessagePart = { "type": "text", text: string, } | { "type": "image", 
/**
 * base64 数据 URL 或远端 URL。
 */
source: string, media_type?: string | null, } | { "type": "file_data", mime_type: string, file_uri: string, } | { "type": "inline_data", mime_type: string, 
/**
 * 已解码的原始字节;backend 内部按需 base64 编码。
 */
data: Array<number>, } | { "type": "tool_use", id: string, name: string, input: JsonValue, } | { "type": "tool_result", tool_use_id: string, content: string, is_error: boolean, };
