// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelInfo = { id: string, display_name: string, capabilities: Array<string>, 
/**
 * 最大上下文 token 数,如果 backend 不能确切给出则为 None。
 */
context_window?: number | null, };
