// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../../rust/crates/rpg-state/bindings/serde_json/JsonValue";

/**
 * 写入操作枚举。所有变更必须通过 [`apply_op`] 走完整闸门。
 *
 * `path` 在内部统一过 [`clean_path`] 做中文别名 / 空白归一。
 */
export type Op = { "op": "set", path: string, value: JsonValue, } | { "op": "delete", path: string, } | { "op": "append", path: string, value: JsonValue, } | { "op": "inc", path: string, delta: number, } | { "op": "merge", path: string, value: JsonValue, };
