// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../../rust/crates/rpg-routes/bindings/serde_json/JsonValue";

/**
 * `chunk` 事件 payload — LLM 流式片段。
 *
 * 目前 game.rs stub 阶段只发 `{ text: "" }`。chat_pipeline 落地后会扩展为
 * `kind: "text" | "thinking" | "tool_call" | "usage" | "stop" | "error"`,
 * 与 [`rpg_llm::pipeline::WireChatChunk`] 对齐(那是 LLM 内部 ChatChunk 的
 * ts-rs 友好 wire 投影)。
 */
export type SseChunkPayload = { 
/**
 * 文本片段(text/thinking/error 公用)。
 */
text: string, 
/**
 * 可选 kind,与 WireChatChunk 对齐(`text` / `thinking` / `tool_call` 等)。
 */
kind?: string | null, 
/**
 * `tool_call` 类:已合并完的 tool 调用 id。
 */
tool_call_id?: string | null, 
/**
 * `tool_call` 类:tool 名称。
 */
tool_name?: string | null, 
/**
 * `tool_call` 类:已合并完的 tool input(JSON object)。
 */
tool_input?: JsonValue | null, };
