// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../../rust/crates/rpg-routes/bindings/serde_json/JsonValue";

/**
 * `done` 事件 payload — 流末尾,可能携带最新 state snapshot。
 */
export type SseDonePayload = { 
/**
 * `{ "state": GameStateData }` 或更宽 payload。typed snapshot 见
 * `frontend/src/types/rust/GameStateData.ts`。
 */
status?: JsonValue | null, 
/**
 * 是否被跨 pod stop 信号中断。
 */
interrupted?: boolean | null, 
/**
 * console_assistant 通用 `{ ok: true }` 简化。
 */
ok?: boolean | null, };
