// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SseChunkPayload } from "./SseChunkPayload";
import type { SseDonePayload } from "./SseDonePayload";
import type { SseErrorPayload } from "./SseErrorPayload";
import type { SseHelloPayload } from "./SseHelloPayload";
import type { SseStateChangePayload } from "./SseStateChangePayload";

/**
 * 顶层 SSE event 信封 — 前端做 discriminated union 用。
 *
 * 注意:后端 [`crate::named_sse_event`] 写出的是裸 `event: xxx` + JSON
 * payload,**不是**整体 envelope JSON。这里给的是 frontend 反序列化后的
 * 逻辑形态:`{ event: "hello", payload: SseHelloPayload }`。
 */
export type SseEnvelope = { "event": "hello", payload: SseHelloPayload, } | { "event": "state_change", payload: SseStateChangePayload, } | { "event": "chunk", payload: SseChunkPayload, } | { "event": "done", payload: SseDonePayload, } | { "event": "error", payload: SseErrorPayload, } | { "event": "keepalive" };
