// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `error` 事件 payload。
 */
export type SseErrorPayload = { 
/**
 * 错误描述(可中文)。
 */
detail: string, 
/**
 * 机器可读 code(`bad_request` / `quota_exceeded` 等)。
 */
code: string, };
