// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `hello` 事件 payload — 与 [`crate::hello_payload`] 同形。
 */
export type SseHelloPayload = { 
/**
 * 当前会话用户 id(匿名时 `"anonymous"`)。
 */
user_id: string, 
/**
 * Unix 秒时间戳。
 */
ts: bigint, 
/**
 * 协议版本号,目前 `"v1"`。
 */
protocol: string, };
