// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `state_change` 事件 payload — 多形,实际由调用点选填字段。
 *
 * 比如:
 * - opening:`{ phase: "generating", label: "GM 构思开场中…" }`
 * - chat:  `{ phase: "generating", label: "GM 思考中…" }`
 * - console_assistant chat:`{ conversation_id: "..." }`
 * - console_assistant confirm:`{ call_id: "...", decision: "approve" }`
 */
export type SseStateChangePayload = { 
/**
 * 通用阶段标签(`generating` / `waiting` / `tool_call` 等)。
 */
phase?: string | null, 
/**
 * 人类可读阶段名(中文)。
 */
label?: string | null, 
/**
 * console_assistant chat 会话 id。
 */
conversation_id?: string | null, 
/**
 * console_assistant confirm 工具调用 id。
 */
call_id?: string | null, 
/**
 * `approve` / `reject` / `cancel` 等。
 */
decision?: string | null, };
