// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../../rust/crates/rpg-routes/bindings/serde_json/JsonValue";

/**
 * `state_change` 事件 — bus 投影 payload。
 *
 * W3-2:`/api/state_events` SSE 通道把 [`rpg_state::StateEvent`] 投影成
 * `{ topic, op, payload, ts }` 形态推给前端,与 Python `state_event_bus.StateEvent.to_sse_data`
 * 保持线上兼容。前端 `state-event-bridge.js` 据 `topic` 派 `rpg-{topic}-updated` CustomEvent。
 *
 * 与 [`SseStateChangePayload`] 区分:那个是流内阶段标签(chat / opening 等),
 * 这个是 bus → 前端的状态总线投影。两者共用同一个 SSE event name 是历史包袱,
 * 前端按字段是否存在区分(`phase` vs `topic`)。
 */
export type SseStateBusPayload = { 
/**
 * 业务 topic(`saves` / `cards` / `personas` / `permissions` / `pending` /
 * `questions` / `timeline` / `worldline` / `state` 等)。
 */
topic: string, 
/**
 * 操作(`updated` / `created` / `deleted` / `applied` / `added` / `resolved`
 * / `answered` / `jump` / `validated` 等)。
 */
op: string, 
/**
 * user_id(防 cross-user 泄漏,前端校验)。
 */
user_id: string, 
/**
 * 关联载荷 — 与具体 [`rpg_state::StateEvent`] 变体相关字段(version / op /
 * pending_id / question_id 等)。
 */
payload: JsonValue, 
/**
 * Unix 秒时间戳。
 */
ts: bigint, };
