// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../../rust/crates/rpg-state/bindings/serde_json/JsonValue";
import type { Op } from "./Op";

/**
 * 状态变更事件。
 *
 * 设计取舍:
 * - `Updated` 是最粗粒度的「state 变了」信号,只带 user_id + version。SSE 端
 *   订阅这个就够触发前端 refetch。
 * - `OpApplied` 携带具体 op,给 LeftRail / audit 实时反馈用。
 * - `PendingAdded` / `PendingResolved` 给审批 UI 用。
 * - `QuestionAdded` / `QuestionAnswered` 给 pending-question 卡片用。
 * - `TimelineJump` / `WorldlineValidation` 给世界线推演 UI 用。
 */
export type StateEvent = { "kind": "updated", user_id: string, version: bigint, } | { "kind": "op_applied", user_id: string, version: bigint, op: Op, source: string, } | { "kind": "pending_added", user_id: string, pending_id: string, path: string, source: string, } | { "kind": "pending_resolved", user_id: string, pending_id: string, approved: boolean, path: string, } | { "kind": "question_added", user_id: string, question_id: string, question: string, source: string, } | { "kind": "question_answered", user_id: string, question_id: string, choice: string | null, } | { "kind": "timeline_jump", user_id: string, anchor_state: string, world_time: string, } | { "kind": "worldline_validation", user_id: string, status: string, message: string, } | { "kind": "custom", user_id: string, 
/**
 * 自定义事件子类型(避免与 serde tag 字段 `kind` 同名)。
 */
event_type: string, payload: JsonValue, };
