// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../../rust/crates/rpg-llm/bindings/serde_json/JsonValue";

export type ToolSchema = { name: string, description: string, 
/**
 * JSONSchema (OpenAPI 风格) 描述 input。
 */
input_schema: JsonValue, 
/**
 * 可选的 server_id (来自 MCP);backend 用作 namespace 前缀。
 */
server_id?: string | null, };
