// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../../rust/crates/rpg-llm/bindings/serde_json/JsonValue";

export type ToolCall = { id: string, name: string, 
/**
 * 已合并完的 JSON object;流式累加由 backend 在拼完后再 emit。
 */
input: JsonValue, };
