// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../../rust/crates/rpg-llm/bindings/serde_json/JsonValue";
import type { Usage } from "./Usage";

/**
 * 前端 SSE 流接收的 chunk wire 形态(命名字段,ts-rs 友好)。
 *
 * `ChatChunk` 是 backend 内部 enum,含 newtype tuple variant(`Text(String)`
 * 等),`#[serde(tag)]` + tuple 在 ts-rs / TS 上无法生成可用类型。本结构是
 * route 层在序列化为 SSE `chunk` event payload 前的 typed wrapper。
 *
 * `kind` 取 `text` / `thinking` / `tool_call` / `usage` / `stop` / `error`,
 * 对应字段按需可空。
 */
export type WireChatChunk = { 
/**
 * chunk 子类型 tag。
 */
kind: string, 
/**
 * `text` / `thinking` / `error` 类:实际文本内容。
 */
text?: string | null, 
/**
 * `tool_call` 类:已合并完的 tool 调用 id。
 */
tool_call_id?: string | null, 
/**
 * `tool_call` 类:tool 名称。
 */
tool_name?: string | null, 
/**
 * `tool_call` 类:已合并完的 tool input(JSON object)。
 */
tool_input?: JsonValue | null, 
/**
 * `usage` 类:token 使用统计。
 */
usage?: Usage | null, 
/**
 * `stop` 类:模型给出的停止原因。
 */
stop_reason?: string | null, };
