// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 客户端 → 服务端消息。
 */
export type WsClientMessage = { "type": "ping", ts: bigint | null, } | { "type": "stop" } | { "type": "typing", typing: boolean, } | { "type": "subscribe", topics: Array<string>, };
