// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `error` payload。
 */
export type WsErrorPayload = { detail: string, code: string, };
