// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `hello` payload — 复用 SSE 形态,加 protocol="ws-v1"。
 */
export type WsHelloPayload = { user_id: string, ts: bigint, protocol: string, };
