// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../../rust/crates/rpg-routes/bindings/serde_json/JsonValue";
import type { SseStateBusPayload } from "./SseStateBusPayload";
import type { WsErrorPayload } from "./WsErrorPayload";
import type { WsHelloPayload } from "./WsHelloPayload";

/**
 * 服务端 → 客户端消息。tagged union(`type` 字段)便于前端 discriminated union。
 *
 * 与 SSE event 名对齐:`hello` / `state_change` / `chunk` / `done` / `error`,
 * 再加 ws 特有的 `pong`(响应 client ping)+ `typing`(广播 typing 状态)。
 */
export type WsServerMessage = { "type": "hello", payload: WsHelloPayload, } | { "type": "state_change", payload: SseStateBusPayload, } | { "type": "chunk", payload: JsonValue, } | { "type": "done", payload: JsonValue, } | { "type": "error", payload: WsErrorPayload, } | { "type": "pong", ts: bigint, } | { "type": "typing", user_id: string, typing: boolean, ts: bigint, };
