// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../rust/crates/rpg-schemas/bindings/serde_json/JsonValue";

/**
 * 一次 `apply_op` 的审计条目。
 *
 * 命中各闸门时 `blocked` 填闸门名(`hard_forbidden` / `rules_managed` /
 * `module_managed`);成功写入时 `op` + `value` + `mode` 填实际写入。
 * 字段顺序贴近旧 `json!({...})` 输出。
 */
export type AuditEntry = { ts: string, source: string, path: string, blocked?: string | null, hint?: string | null, op?: string | null, value?: JsonValue | null, mode?: string | null, turn: bigint, };
