// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../rust/crates/rpg-schemas/bindings/serde_json/JsonValue";

export type Encounter = { active: boolean, round: bigint, turn_index: bigint, initiative_order: Array<JsonValue>, combatants: Array<JsonValue>, encounter_id: string, log: Array<JsonValue>, };
