// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../rust/crates/rpg-schemas/bindings/serde_json/JsonValue";
import type { Encounter } from "./Encounter";
import type { Memory } from "./Memory";
import type { PermissionsState } from "./PermissionsState";
import type { PlayerCharacter } from "./PlayerCharacter";
import type { PlayerInfo } from "./PlayerInfo";
import type { PlayerPrivate } from "./PlayerPrivate";
import type { Ruleset } from "./Ruleset";
import type { Scene } from "./Scene";
import type { World } from "./World";
import type { Worldline } from "./Worldline";

/**
 * 与旧 `rpg-state::default_state()` 同形的顶层游戏状态数据。
 *
 * 字段顺序刻意贴近旧 JSON,序列化输出友好。
 */
export type GameStateData = { schema_version: bigint, ruleset: Ruleset, player_character: PlayerCharacter, scene: Scene, encounter: Encounter, dice_log: Array<JsonValue>, active_entities: Array<JsonValue>, player: PlayerInfo, player_private: PlayerPrivate, world: World, relationships: { [key in string]: JsonValue }, history: Array<JsonValue>, permissions: PermissionsState, worldline: Worldline, memory: Memory, turn: bigint, is_new: boolean, 
/**
 * ISO8601。旧代码用空串占位,这里跟随。
 */
created_at: string, };
