// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../rust/crates/rpg-schemas/bindings/serde_json/JsonValue";

export type Memory = { mode: string, main_quest: string, current_objective: string, resources: Array<JsonValue>, abilities: Array<JsonValue>, facts: Array<JsonValue>, pinned: Array<JsonValue>, notes: Array<JsonValue>, items: Array<JsonValue>, last_retrieval: string, last_context: { [key in string]: JsonValue }, last_context_agent: { [key in string]: JsonValue }, last_structured_updates: Array<JsonValue>, };
