// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../rust/crates/rpg-schemas/bindings/serde_json/JsonValue";

/**
 * 写入待审条目(权限模式不放行 + 未 force 时落到 pending)。
 */
export type PendingWrite = { id: string, path: string, value: JsonValue, op: string, source: string, turn: bigint, from: JsonValue, to: JsonValue, reason: string, };
