// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../rust/crates/rpg-schemas/bindings/serde_json/JsonValue";
import type { AuditEntry } from "./AuditEntry";
import type { PendingWrite } from "./PendingWrite";

export type PermissionsState = { mode: string, pending_writes: Array<PendingWrite>, pending_questions: Array<JsonValue>, audit_log: Array<AuditEntry>, };
