// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../rust/crates/rpg-schemas/bindings/serde_json/JsonValue";

export type PlayerPrivate = { secrets: Array<JsonValue>, flags: { [key in string]: JsonValue }, hidden_traits: Array<JsonValue>, story_intent: string, };
