// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlayerInfo = { name: string, role: string, background: string, current_location: string, };
