// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../rust/crates/rpg-schemas/bindings/serde_json/JsonValue";

export type PlayerCharacter = { name: string, level: number, class_name: string, species: string, background: string, abilities: { [key in string]: JsonValue }, proficiency_bonus: number, skills: { [key in string]: JsonValue }, saves: { [key in string]: JsonValue }, max_hp: number, hp: number, ac: number, inventory: Array<JsonValue>, conditions: Array<JsonValue>, features: Array<JsonValue>, weapons: { [key in string]: JsonValue }, };
