// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../rust/crates/rpg-schemas/bindings/serde_json/JsonValue";

export type Scene = { module_id: string, location_id: string, visited_rooms: Array<JsonValue>, exits: Array<JsonValue>, visible_clues: Array<JsonValue>, flags: { [key in string]: JsonValue }, };
