// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../rust/crates/rpg-schemas/bindings/serde_json/JsonValue";

export type TimelineState = { anchor_state: string, current_label: string, current_phase: string, anchor_source: string, anchor_turn: bigint, pending_jump: JsonValue | null, last_transition: JsonValue | null, };
