// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../rust/crates/rpg-schemas/bindings/serde_json/JsonValue";
import type { WorldlineValidation } from "./WorldlineValidation";

export type Worldline = { user_variables: { [key in string]: JsonValue }, divergence_chapter: bigint | null, constraints: Array<string>, last_projection: JsonValue | null, pending_projection: JsonValue | null, last_validation: WorldlineValidation, custom_ui: { [key in string]: JsonValue }, };
