// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../rust/crates/rpg-schemas/bindings/serde_json/JsonValue";
import type { TimelineState } from "./TimelineState";

export type World = { time: string, timeline: TimelineState, known_events: Array<JsonValue>, };
