from __future__ import annotations

import os
import threading

from platform_app.db.connection import connect
from platform_app.db.migrations import (
    _apply_versioned_migrations,
    _assert_schema_up_to_date,
    _migration_advisory_lock,
)
from platform_app.db.pgvector import try_enable_pgvector

_DB_INITED = False
_DB_INIT_LOCK = threading.Lock()


def init_db(force: bool = False) -> None:
    """启动时执行一次 schema 创建 + migration；请求路径调用直接 short-circuit。

    历史上每个 endpoint 都调 init_db() 触发 DDL，会与并发 login/register 的
    schema lock 撞死锁。现在请求路径只读 _DB_INITED flag 立即返回，DDL 只在
    module load / 显式 reset 时跑一次。force=True 用于运维强制重新跑 migration。

    生产部署（推荐）：设置 RPG_SKIP_AUTO_MIGRATE=1，由 deploy 脚本提前手动跑：
      - 首次部署 fresh DB:  python -m platform_app.migrate full   ← 必须 full，不能 up
      - 后续升级有历史 DB:  python -m platform_app.migrate up
      详见 platform_app/migrate.py 顶部注释和 deploy/bare-metal/README.md §5/§11。

    !! migration 不走 PgBouncer（transaction 池不支持 pg_advisory_lock）!!
       DATABASE_URL 跑 migrate 时应指向直连 5432；运行时 uvicorn 才走 PgBouncer 6432。

    若 schema 落后于代码里登记的 MIGRATIONS 列表，init_db 会 fail-fast。
    """
    global _DB_INITED
    if _DB_INITED and not force:
        return
    with _DB_INIT_LOCK:
        if _DB_INITED and not force:
            return
        from core.config import skip_auto_migrate as _skip_auto_migrate
        if _skip_auto_migrate():
            # 仅做版本检查：schema 落后就 raise
            _assert_schema_up_to_date()
        else:
            # 取 advisory lock，串行化 DDL，防止多 worker / 多进程同时建表撞锁
            with _migration_advisory_lock():
                _do_init_db()
                _apply_versioned_migrations()
                try_enable_pgvector()
        _DB_INITED = True


def reset_db_init_flag() -> None:
    """单元测试用：强制下次 init_db 重新跑"""
    global _DB_INITED
    _DB_INITED = False


def _do_init_db() -> None:
    """实际的 DDL 跑批，不要直接调，走 init_db()"""
    with connect() as db:
        db.execute("create extension if not exists pgcrypto")
        db.execute("create extension if not exists pg_trgm")
        db.execute(
            """
            create table if not exists users (
              id bigint generated by default as identity primary key,
              username text unique not null,
              password_hash text not null,
              display_name text not null,
              bio text not null default '',
              role text not null default 'user',
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now()
            )
            """
        )
        db.execute(
            """
            create table if not exists sessions (
              token text primary key,
              user_id bigint not null references users(id) on delete cascade,
              created_at timestamptz not null default now(),
              expires_at timestamptz not null
            )
            """
        )
        db.execute(
            """
            create table if not exists scripts (
              id bigint generated by default as identity primary key,
              owner_id bigint not null references users(id) on delete cascade,
              title text not null,
              description text not null default '',
              source_path text not null default '',
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now()
            )
            """
        )
        db.execute(
            """
            create table if not exists game_saves (
              id bigint generated by default as identity primary key,
              user_id bigint not null references users(id) on delete cascade,
              script_id bigint not null references scripts(id) on delete cascade,
              title text not null,
              state_path text not null,
              active_branch_node_id bigint,
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now()
            )
            """
        )
        db.execute(
            """
            create table if not exists branch_nodes (
              id bigint generated by default as identity primary key,
              save_id bigint not null references game_saves(id) on delete cascade,
              parent_id bigint references branch_nodes(id) on delete cascade,
              turn_index integer not null,
              role text not null,
              title text not null,
              summary text not null default '',
              content_preview text not null default '',
              state_path text not null default '',
              created_at timestamptz not null default now()
            )
            """
        )
        db.execute(
            """
            create table if not exists branch_commits (
              id bigint generated by default as identity primary key,
              save_id bigint not null references game_saves(id) on delete cascade,
              parent_id bigint references branch_commits(id) on delete cascade,
              object_hash text not null,
              tree_hash text not null default '',
              turn_index integer not null,
              kind text not null,
              title text not null,
              message text not null default '',
              summary text not null default '',
              content_preview text not null default '',
              state_path text not null default '',
              player_input text not null default '',
              gm_output text not null default '',
              metadata jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now(),
              unique(save_id, object_hash)
            )
            """
        )
        # task 107A: branch_commits 加 2 列 — 追踪每个 commit 是否已被 phase 摘要纳入
        db.execute(
            """
            alter table branch_commits
              add column if not exists digested_in_phase integer,
              add column if not exists digest_at timestamptz
            """
        )
        db.execute(
            """
            alter table game_saves
              add column if not exists active_phase_index integer not null default 0
            """
        )
        # task 107A: save 级阶段摘要 — 每 N turn 一段 LLM 摘要,GM 长游戏不失忆
        db.execute(
            """
            create table if not exists save_phase_digests (
              id bigint generated by default as identity primary key,
              save_id bigint not null references game_saves(id) on delete cascade,
              phase_index integer not null,
              turn_start integer not null,
              turn_end integer not null,
              story_time_label text not null default '',
              phase_label text not null default '',
              summary text not null default '',
              key_events jsonb not null default '[]'::jsonb,
              key_npcs jsonb not null default '[]'::jsonb,
              key_locations jsonb not null default '[]'::jsonb,
              key_decisions jsonb not null default '[]'::jsonb,
              emotion_arc text not null default '',
              status text not null default 'open',
              generated_by text not null default 'llm',
              metadata jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now(),
              unique(save_id, phase_index)
            )
            """
        )
        db.execute(
            "create index if not exists idx_save_phase_digests_save on save_phase_digests(save_id, phase_index)"
        )
        # task 107A: save 级时间锚点 — 每 turn 一个故事时间标签,对应 script_timeline_anchors
        db.execute(
            """
            create table if not exists save_timeline_anchors (
              id bigint generated by default as identity primary key,
              save_id bigint not null references game_saves(id) on delete cascade,
              turn_index integer not null,
              story_time_label text not null,
              phase_label text not null default '',
              source text not null default 'gm',
              delta_label text not null default '',
              metadata jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now(),
              unique(save_id, turn_index)
            )
            """
        )
        db.execute(
            "create index if not exists idx_save_timeline_save on save_timeline_anchors(save_id, turn_index)"
        )
        # task 107A: save 级世界书 overlay
        # 设计原则: 剧本 worldbook 只来自导入,运行时不修改。
        # overlay 只支持 'addition' (新增) + 'retirement' (停用某剧本 entry)。
        db.execute(
            """
            create table if not exists save_worldbook_overlays (
              id bigint generated by default as identity primary key,
              save_id bigint not null references game_saves(id) on delete cascade,
              kind text not null,
              title text not null default '',
              content text not null default '',
              keys jsonb not null default '[]'::jsonb,
              priority integer not null default 50,
              retired_entry_id bigint,
              retired_reason text not null default '',
              introduced_turn integer,
              metadata jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now(),
              check (kind in ('addition', 'retirement')),
              check ((kind = 'addition' and title <> '') or
                     (kind = 'retirement' and retired_entry_id is not null))
            )
            """
        )
        db.execute(
            "create index if not exists idx_save_wb_overlay_save on save_worldbook_overlays(save_id, kind)"
        )
        db.execute(
            "create index if not exists idx_save_wb_overlay_retired on save_worldbook_overlays(retired_entry_id) where retired_entry_id is not null"
        )
        db.execute(
            """
            create table if not exists branch_refs (
              id bigint generated by default as identity primary key,
              save_id bigint not null references game_saves(id) on delete cascade,
              name text not null,
              kind text not null default 'head',
              target_commit_id bigint references branch_commits(id) on delete set null,
              is_active boolean not null default false,
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now(),
              unique(save_id, name)
            )
            """
        )
        db.execute(
            """
            create table if not exists runtime_checkouts (
              id bigint generated by default as identity primary key,
              user_id bigint not null references users(id) on delete cascade,
              save_id bigint not null references game_saves(id) on delete cascade,
              ref_id bigint references branch_refs(id) on delete set null,
              commit_id bigint references branch_commits(id) on delete set null,
              runtime_state_path text not null default '',
              updated_at timestamptz not null default now(),
              unique(user_id, save_id)
            )
            """
        )
        db.execute(
            """
            create table if not exists settings (
              user_id bigint not null references users(id) on delete cascade,
              key text not null,
              value jsonb not null,
              updated_at timestamptz not null default now(),
              primary key (user_id, key)
            )
            """
        )
        db.execute(
            """
            create table if not exists assets (
              id bigint generated by default as identity primary key,
              user_id bigint not null references users(id) on delete cascade,
              name text not null,
              rel_path text not null,
              mime text not null,
              kind text not null,
              size bigint not null,
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now()
            )
            """
        )
        db.execute(
            """
            create table if not exists script_chapters (
              id bigint generated by default as identity primary key,
              script_id bigint not null references scripts(id) on delete cascade,
              chapter_index integer not null,
              title text not null,
              content text not null,
              word_count integer not null default 0,
              volume_title text not null default '',
              source_marker text not null default '',
              confidence real not null default 0,
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now(),
              unique(script_id, chapter_index)
            )
            """
        )
        db.execute(
            """
            create table if not exists books (
              id bigint generated by default as identity primary key,
              owner_id bigint not null references users(id) on delete cascade,
              script_id bigint unique references scripts(id) on delete cascade,
              title text not null,
              slug text not null,
              description text not null default '',
              default_language text not null default 'zh-CN',
              metadata jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now(),
              unique(owner_id, slug)
            )
            """
        )
        db.execute(
            """
            create table if not exists documents (
              id bigint generated by default as identity primary key,
              book_id bigint not null references books(id) on delete cascade,
              script_id bigint not null references scripts(id) on delete cascade,
              chapter_id bigint references script_chapters(id) on delete cascade,
              source_kind text not null default 'chapter',
              source_ref text not null,
              title text not null default '',
              content text not null,
              metadata jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now(),
              unique(book_id, source_kind, source_ref)
            )
            """
        )
        db.execute(
            """
            create table if not exists document_chunks (
              id bigint generated by default as identity primary key,
              document_id bigint not null references documents(id) on delete cascade,
              book_id bigint not null references books(id) on delete cascade,
              script_id bigint not null references scripts(id) on delete cascade,
              chapter_id bigint references script_chapters(id) on delete cascade,
              chapter_index integer not null default 0,
              chunk_index integer not null,
              content text not null,
              token_count integer not null default 0,
              embedding jsonb,
              embedding_model text not null default '',
              search_tsv tsvector generated always as (to_tsvector('simple', content)) stored,
              metadata jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now(),
              unique(document_id, chunk_index)
            )
            """
        )
        db.execute(
            """
            create table if not exists chapter_facts (
              id bigint generated by default as identity primary key,
              book_id bigint not null references books(id) on delete cascade,
              script_id bigint not null references scripts(id) on delete cascade,
              document_id bigint references documents(id) on delete cascade,
              chapter_id bigint references script_chapters(id) on delete cascade,
              chapter integer not null,
              title text not null default '',
              viewpoint text not null default '',
              summary text not null default '',
              story_phase text not null default '',
              story_time_label text not null default '',
              scene_count integer not null default 0,
              token_estimate integer not null default 0,
              characters jsonb not null default '[]'::jsonb,
              locations jsonb not null default '[]'::jsonb,
              factions jsonb not null default '[]'::jsonb,
              concepts jsonb not null default '[]'::jsonb,
              items jsonb not null default '[]'::jsonb,
              relationships jsonb not null default '[]'::jsonb,
              events jsonb not null default '[]'::jsonb,
              confidence numeric(4,3) not null default 0.500,
              metadata jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now(),
              unique(script_id, chapter)
            )
            """
        )
        db.execute(
            """
            create table if not exists character_cards (
              id bigint generated by default as identity primary key,
              book_id bigint not null references books(id) on delete cascade,
              script_id bigint not null references scripts(id) on delete cascade,
              name text not null,
              aliases jsonb not null default '[]'::jsonb,
              identity text not null default '',
              appearance text not null default '',
              personality text not null default '',
              speech_style text not null default '',
              current_status text not null default '',
              secrets text not null default '',
              sample_dialogue jsonb not null default '[]'::jsonb,
              token_budget integer not null default 450,
              priority integer not null default 100,
              enabled boolean not null default true,
              metadata jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now(),
              unique(script_id, name)
            )
            """
        )
        db.execute(
            """
            create table if not exists worldbook_entries (
              id bigint generated by default as identity primary key,
              book_id bigint not null references books(id) on delete cascade,
              script_id bigint not null references scripts(id) on delete cascade,
              title text not null,
              content text not null,
              keys jsonb not null default '[]'::jsonb,
              regex_keys jsonb not null default '[]'::jsonb,
              priority integer not null default 50,
              token_budget integer not null default 600,
              insertion_position text not null default 'worldbook',
              sticky_turns integer not null default 0,
              cooldown_turns integer not null default 0,
              probability numeric(5,2) not null default 100.00,
              character_filter jsonb not null default '[]'::jsonb,
              scene_filter jsonb not null default '[]'::jsonb,
              enabled boolean not null default true,
              metadata jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now(),
              unique(script_id, title)
            )
            """
        )
        db.execute(
            """
            create table if not exists game_sessions (
              id bigint generated by default as identity primary key,
              save_id bigint unique references game_saves(id) on delete cascade,
              book_id bigint references books(id) on delete set null,
              script_id bigint references scripts(id) on delete cascade,
              user_id bigint not null references users(id) on delete cascade,
              title text not null default '未命名会话',
              model_name text not null default '',
              state jsonb not null default '{}'::jsonb,
              memory_mode text not null default 'normal',
              permission_mode text not null default 'full_access',
              worldline jsonb not null default '{}'::jsonb,
              turn integer not null default 0,
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now()
            )
            """
        )
        db.execute(
            """
            create table if not exists messages (
              id bigint generated by default as identity primary key,
              session_id bigint not null references game_sessions(id) on delete cascade,
              save_id bigint references game_saves(id) on delete cascade,
              turn integer not null,
              role text not null check (role in ('system', 'user', 'assistant', 'tool')),
              content text not null,
              metadata jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now()
            )
            """
        )
        db.execute(
            """
            create table if not exists memories (
              id bigint generated by default as identity primary key,
              session_id bigint references game_sessions(id) on delete cascade,
              book_id bigint references books(id) on delete cascade,
              user_id bigint references users(id) on delete cascade,
              bucket text not null check (bucket in ('pinned', 'facts', 'abilities', 'resources', 'notes', 'summary')),
              content text not null,
              importance integer not null default 50,
              source_message_id bigint references messages(id) on delete set null,
              embedding jsonb,
              embedding_model text not null default '',
              metadata jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now()
            )
            """
        )
        db.execute(
            """
            create table if not exists worldline_variables (
              id bigint generated by default as identity primary key,
              session_id bigint not null references game_sessions(id) on delete cascade,
              key text not null,
              value text not null,
              locked boolean not null default true,
              source text not null default 'user',
              metadata jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now(),
              unique(session_id, key)
            )
            """
        )
        db.execute(
            """
            create table if not exists worldline_projections (
              id bigint generated by default as identity primary key,
              session_id bigint not null references game_sessions(id) on delete cascade,
              turn integer not null,
              projection text not null,
              validated boolean not null default false,
              validation_status text not null default 'none',
              variables_snapshot jsonb not null default '{}'::jsonb,
              metadata jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now()
            )
            """
        )
        db.execute(
            """
            create table if not exists context_runs (
              id bigint generated by default as identity primary key,
              session_id bigint references game_sessions(id) on delete cascade,
              save_id bigint references game_saves(id) on delete cascade,
              user_id bigint references users(id) on delete cascade,
              turn integer not null default 0,
              user_input text not null,
              agent_steps jsonb not null default '[]'::jsonb,
              curator_plan jsonb not null default '{}'::jsonb,
              layers jsonb not null default '[]'::jsonb,
              active_character_cards jsonb not null default '[]'::jsonb,
              active_worldbook jsonb not null default '[]'::jsonb,
              retrieved_chunks jsonb not null default '[]'::jsonb,
              estimated_tokens integer not null default 0,
              cache_plan jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now()
            )
            """
        )
        db.execute(
            """
            create table if not exists app_config (
              key text primary key,
              value jsonb not null,
              updated_at timestamptz not null default now()
            )
            """
        )
        db.execute(
            """
            create table if not exists model_apis (
              api_id text primary key,
              display_name text not null,
              kind text not null,
              enabled boolean not null default true,
              credential_ref text not null default '',
              credential_env text not null default '',
              metadata jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now()
            )
            """
        )
        db.execute(
            """
            create table if not exists model_entries (
              id bigint generated by default as identity primary key,
              api_id text not null references model_apis(api_id) on delete cascade,
              model_id text not null,
              real_name text not null,
              display_name text not null,
              enabled boolean not null default true,
              capabilities jsonb not null default '[]'::jsonb,
              metadata jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now(),
              unique(api_id, model_id)
            )
            """
        )
        db.execute(
            """
            create table if not exists mcp_servers (
              server_id text primary key,
              display_name text not null,
              transport text not null default 'stdio',
              command text not null default '',
              args jsonb not null default '[]'::jsonb,
              env jsonb not null default '{}'::jsonb,
              enabled boolean not null default false,
              scope text not null default 'local',
              metadata jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now()
            )
            """
        )
        db.execute(
            """
            create table if not exists imported_skills (
              skill_id text primary key,
              name text not null,
              path text not null,
              enabled boolean not null default true,
              metadata jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now()
            )
            """
        )
        for table in (
            "users",
            "scripts",
            "game_saves",
            "branch_nodes",
            "branch_commits",
            "branch_refs",
            "runtime_checkouts",
            "assets",
            "script_chapters",
            "books",
            "documents",
            "document_chunks",
            "chapter_facts",
            "character_cards",
            "worldbook_entries",
            "game_sessions",
            "messages",
            "memories",
            "worldline_variables",
            "worldline_projections",
            "context_runs",
            "model_entries",
        ):
            db.execute(f"alter table {table} add column if not exists public_id uuid not null default gen_random_uuid()")
            db.execute(f"alter table {table} add column if not exists row_version bigint not null default 1")
            db.execute(f"create unique index if not exists idx_{table}_public_id on {table}(public_id)")
        db.execute("alter table users add column if not exists updated_at timestamptz not null default now()")
        db.execute("alter table scripts add column if not exists chapter_count integer not null default 0")
        db.execute("alter table scripts add column if not exists word_count integer not null default 0")
        db.execute("alter table scripts add column if not exists import_report jsonb not null default '{}'::jsonb")
        db.execute("alter table branch_nodes add column if not exists summary text not null default ''")
        db.execute("alter table branch_commits add column if not exists state_snapshot jsonb not null default '{}'::jsonb")
        db.execute("alter table game_saves add column if not exists active_branch_ref_id bigint")
        db.execute("alter table game_saves add column if not exists active_commit_id bigint")
        db.execute("alter table game_saves add column if not exists state_snapshot jsonb not null default '{}'::jsonb")
        db.execute("alter table runtime_checkouts add column if not exists state_snapshot jsonb not null default '{}'::jsonb")
        db.execute("alter table runtime_checkouts add column if not exists snapshot_hash text not null default ''")
        db.execute("alter table runtime_checkouts add column if not exists dirty boolean not null default false")
        db.execute("alter table runtime_checkouts add column if not exists turn_at_commit integer not null default 0")
        db.execute("alter table runtime_checkouts add column if not exists turn_runtime integer not null default 0")
        db.execute("alter table context_runs add column if not exists status text not null default 'done'")
        db.execute("alter table context_runs add column if not exists error text not null default ''")
        db.execute("alter table context_runs add column if not exists duration_ms integer not null default 0")
        db.execute("alter table context_runs add column if not exists started_at timestamptz not null default now()")
        db.execute("alter table assets add column if not exists updated_at timestamptz not null default now()")
        db.execute("create index if not exists idx_sessions_user_expires on sessions(user_id, expires_at desc)")
        db.execute("create index if not exists idx_scripts_owner_updated on scripts(owner_id, updated_at desc, id desc)")
        db.execute("create index if not exists idx_scripts_owner_title on scripts(owner_id, lower(title))")
        db.execute("create index if not exists idx_saves_user on game_saves(user_id, updated_at desc, id desc)")
        db.execute("create index if not exists idx_saves_user_script on game_saves(user_id, script_id, id desc)")
        db.execute("create index if not exists idx_branch_save on branch_nodes(save_id, id)")
        db.execute("create index if not exists idx_branch_parent on branch_nodes(parent_id)")
        db.execute("create index if not exists idx_branch_save_turn on branch_nodes(save_id, turn_index, id)")
        db.execute("create index if not exists idx_branch_commits_save on branch_commits(save_id, id)")
        db.execute("create index if not exists idx_branch_commits_parent on branch_commits(parent_id)")
        db.execute("create index if not exists idx_branch_commits_save_turn on branch_commits(save_id, turn_index, id)")
        db.execute("create index if not exists idx_branch_refs_save on branch_refs(save_id, id)")
        db.execute("create index if not exists idx_branch_refs_target on branch_refs(target_commit_id)")
        db.execute("create index if not exists idx_runtime_checkouts_user_save on runtime_checkouts(user_id, save_id)")
        db.execute("create index if not exists idx_settings_user_updated on settings(user_id, updated_at desc)")
        db.execute("create index if not exists idx_assets_user on assets(user_id, id desc)")
        db.execute("create index if not exists idx_assets_user_kind_created on assets(user_id, kind, created_at desc)")
        db.execute("create index if not exists idx_assets_user_path on assets(user_id, rel_path)")
        db.execute("create index if not exists idx_script_chapters_script_order on script_chapters(script_id, chapter_index)")
        db.execute("create index if not exists idx_script_chapters_title on script_chapters(script_id, lower(title))")
        db.execute("create index if not exists idx_books_owner_updated on books(owner_id, updated_at desc, id desc)")
        db.execute("create index if not exists idx_documents_book_ref on documents(book_id, source_kind, source_ref)")
        db.execute("create index if not exists idx_document_chunks_book_chapter on document_chunks(book_id, chapter_index, chunk_index)")
        db.execute("create index if not exists idx_document_chunks_script_chapter on document_chunks(script_id, chapter_index, chunk_index)")
        db.execute("create index if not exists idx_document_chunks_search on document_chunks using gin(search_tsv)")
        db.execute("create index if not exists idx_document_chunks_trgm on document_chunks using gin(content gin_trgm_ops)")
        db.execute("create index if not exists idx_chapter_facts_book_chapter on chapter_facts(book_id, chapter)")
        db.execute("create index if not exists idx_chapter_facts_script_time on chapter_facts(script_id, story_phase, story_time_label)")
        db.execute("create index if not exists idx_chapter_facts_events on chapter_facts using gin(events)")
        db.execute("create index if not exists idx_character_cards_script on character_cards(script_id, enabled, priority desc)")
        db.execute("create index if not exists idx_worldbook_script_enabled on worldbook_entries(script_id, enabled, priority desc)")
        db.execute("create index if not exists idx_game_sessions_user_book on game_sessions(user_id, book_id)")
        db.execute("create index if not exists idx_messages_session_turn on messages(session_id, turn, created_at)")
        db.execute("create index if not exists idx_memories_session_bucket on memories(session_id, bucket, importance desc)")
        db.execute("create index if not exists idx_worldline_variables_session on worldline_variables(session_id)")
        db.execute("create index if not exists idx_worldline_projections_session_turn on worldline_projections(session_id, turn desc)")
        db.execute("create index if not exists idx_context_runs_session_turn on context_runs(session_id, turn desc)")
        db.execute("create index if not exists idx_model_entries_api on model_entries(api_id, enabled, id)")
        db.execute("create index if not exists idx_mcp_servers_enabled on mcp_servers(enabled, server_id)")
        db.execute("create index if not exists idx_imported_skills_enabled on imported_skills(enabled, skill_id)")

    # 注：版本化 migration 和 pgvector 扩展由 init_db()/migrate.py 统一在
    # advisory lock 内调用，这里不重复触发。
