// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * catalog 数据来源,前端 UI 用于显示"实时/缓存/用户改写"。
 */
export type CatalogSource = "LiveApi" | "StaticCatalog" | "UserOverride" | "OpenRouterProxy";
