// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 模型能力 bit-set。所有字段默认 false,catalog 显式设 true。
 */
export type ModelCapabilities = { streaming: boolean, tools: boolean, vision: boolean, audio: boolean, structured_output: boolean, extended_thinking: boolean, embedding: boolean, function_calling: boolean, prompt_caching: boolean, web_search: boolean, pdf_input: boolean, };
