// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogSource } from "./CatalogSource";
import type { ModelCapabilities } from "./ModelCapabilities";
import type { ProviderId } from "./ProviderId";

/**
 * 单个模型的元数据(对应 /models 返回的一条 + capability/pricing 富信息)。
 */
export type ModelInfo = { id: string, provider: ProviderId, display_name: string, context_window: number | null, max_output_tokens: number | null, input_cost_per_million: number | null, output_cost_per_million: number | null, cache_write_cost_per_million: number | null, cache_read_cost_per_million: number | null, capabilities: ModelCapabilities, unsupported_params: Array<string>, deprecated_at: string | null, retiring_at: string | null, source: CatalogSource, last_updated: string, };
