// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 已对接 provider 的标识。后续 Wave 加新 provider 在此追加。
 */
export type ProviderId = "OpenAI" | "Anthropic" | "GoogleAIStudio" | "AgentPlatform" | "OpenRouter" | "DeepSeek" | "XAi" | "XiaomiMimo" | "AlibabaQwen" | "TencentHunyuan";
